5 core get api articles
Dominic20227/northcoders-news-api pull request #5
Opened 2023-11-21 11:42 UTC by Dominic20227

completed challenge 5

2023-11-21 11:53 UTC, nc-verity-gregory requested changes
This is close but not quite finished. You'll need to test that the returned order is correct and you aren't currently doing that.

2023-11-21 11:53 UTC, nc-verity-gregory commented on __tests__/app.test.js
> +  db.end();
this won't end the connection without a return as it is on a new line, same as the function above.

2023-11-21 11:53 UTC, nc-verity-gregory commented on __tests__/app.test.js
> +        console.log("article 🙃", articles);
Don't leave console logs in code you want reviewed please.

2023-11-21 11:53 UTC, nc-verity-gregory commented on __tests__/app.test.js
> +        articles.forEach((article) => {
If you're going to use a forEach we also need to assert that there is a length so that this does not pass as a false positive.

2023-11-21 11:53 UTC, nc-verity-gregory commented on __tests__/app.test.js
> +  it("retrieves array of articles in decending order by date", () => {
You are asserting that they are in the correct order in your description but have not tested for that.

2023-11-21 11:53 UTC, nc-verity-gregory commented on model/model.js
> +// return db
Please don't leave in commented out code that you're not using.

2023-11-22 11:11 UTC, Hard-Luck approved these changes
Good work, I think your order checking could be cleaner, check my comment

2023-11-22 11:11 UTC, Hard-Luck commented on __tests__/app.test.js
> +          }
This feels a bit hacky, you could have expected articles[i].created_at tobelessthan articles[i + 1].created_at

2023-11-22 11:11 UTC, Hard-Luck commented on __tests__/app.test.js
> +          }
or better yet, jest-sorted

2023-11-22 13:47 UTC, nc-hev-mag commented on model/model.js
> +FROM
Nice SQL!

2023-11-22 13:48 UTC, nc-hev-mag commented on __tests__/app.test.js
> +
Would be good to assert that each article does not contain a body too

2023-11-22 13:48 UTC, nc-hev-mag approved these changes
Nice one Dominic! good to merge

2023-11-23 10:00 UTC, merged